using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using ArcGIS.Core.CIM;
using ArcGIS.Core.Data;
using ArcGIS.Core.Geometry;
using ArcGIS.Desktop.Core;
using ArcGIS.Desktop.Framework;
using ArcGIS.Desktop.Framework.Contracts;
using ArcGIS.Desktop.Framework.Threading.Tasks;
using ArcGIS.Desktop.Mapping;
using ArcGIS.Desktop.Mapping.Events;
using ArcGIS.Desktop.Framework.Events;
using Microsoft.Win32;
using XIAOFUTools.Shared;

namespace XIAOFUTools.Features.Conversion.FeatureToTxt
{
    /// <summary>
    /// 字段显示信息类
    /// </summary>
    public class FieldDisplayInfo
    {
        public string FieldName { get; set; }
        public string Alias { get; set; }
        public string FieldType { get; set; }

        public string DisplayText => string.IsNullOrEmpty(Alias) || Alias == FieldName
            ? $"{FieldName}（{FieldType}）"
            : $"{FieldName}（{Alias}）（{FieldType}）";

        public override string ToString() => DisplayText;
    }

    /// <summary>
    /// 输出字段项类
    /// </summary>
    public class OutputFieldItem : PropertyChangedBase
    {
        private string _fieldName;
        public string FieldName
        {
            get => _fieldName;
            set => SetProperty(ref _fieldName, value);
        }

        private string _description;
        public string Description
        {
            get => _description;
            set => SetProperty(ref _description, value);
        }

        private bool _isEnabled = true;
        public bool IsEnabled
        {
            get => _isEnabled;
            set => SetProperty(ref _isEnabled, value);
        }

        private bool _canDelete = true;
        public bool CanDelete
        {
            get => _canDelete;
            set => SetProperty(ref _canDelete, value);
        }

        private bool _isAutoGenerated = false;
        public bool IsAutoGenerated
        {
            get => _isAutoGenerated;
            set => SetProperty(ref _isAutoGenerated, value);
        }

        public OutputFieldItem(string fieldName, string description, bool canDelete = true, bool isAutoGenerated = false)
        {
            FieldName = fieldName;
            Description = description;
            CanDelete = canDelete;
            IsAutoGenerated = isAutoGenerated;
        }
    }

    /// <summary>
    /// 要素类转TXT DockPane视图模型
    /// </summary>
    internal partial class FeatureToTxtDockPaneViewModel : PropertyChangedBase
    {
        private dynamic _mapSelectionChangedToken;
        private readonly IFeatureToTxtDialogService _dialogService = new FeatureToTxtDialogService();

        // 取消操作标志
        private bool _cancelRequested = false;

        // 是否正在处理
        private bool _isProcessing = false;

        // 面图层列表
        private ObservableCollection<FeatureLayer> _polygonLayers;

        // 选中的面图层
        private FeatureLayer _selectedPolygonLayer;

        // 选择集控制与信息（参考 要素顺序编号/地块中文编号）
        private bool _useSelection = true;

        private bool _hasSelectionInLayer;

        private int _selectedCount;

        private string _selectionInfoText = "全部要素";

        // 输出路径
        private string _outputPath = "";

        // 字段信息列表
        private ObservableCollection<FieldDisplayInfo> _fieldInfos;

        // 输出字段配置集合
        private ObservableCollection<OutputFieldItem> _outputFields;

        // 当前选中的输出字段（用于上移/下移/删除）
        private OutputFieldItem _selectedOutputField;

        // 选项设置
        private bool _outputClosingPoint = true;

        private bool _innerRingStartFromOne = false;

        private bool _closingPointContinueNumbering = false;

        private bool _exportSeparately = false;

        private bool _enableDetailedLogging = true;

        private bool _swapXY = false;

        // 按字段分组导出
        private bool _groupByField = false;

        private string _groupByFieldName = "";

        // 其他设置
        private string _prefix = "J";

        private int _decimalPlaces = 3;

        private ObservableCollection<string> _textFormats;

        private string _selectedTextFormat = "ANSI";

        // 进度值
        private int _progress = 0;

        // 进度条是否不确定
        private bool _isProgressIndeterminate = false;

        // 状态消息
        private string _statusMessage = "请选择面图层。";

        // 日志内容
        private string _logContent = "";

        // 头部信息配置列表
        private ObservableCollection<HeaderConfig> _headerConfigs;

        // 选中的头部信息配置
        private HeaderConfig _selectedHeaderConfig;

        // 运行命令
        private ICommand _runCommand;

        // 取消命令
        private ICommand _cancelCommand;

        // 浏览输出路径命令
        private ICommand _browseOutputPathCommand;



        // 刷新图层命令
        private ICommand _refreshLayersCommand;

        // 删除输出字段命令
        private ICommand _removeOutputFieldCommand;

        // 删除当前选中输出字段命令（快捷）
        private ICommand _removeSelectedOutputFieldCommand;

        // 添加输出字段命令
        private ICommand _addOutputFieldCommand;

        // 上移/下移命令
        private ICommand _moveUpCommand;

        private ICommand _moveDownCommand;

        // 清空全部输出字段
        private ICommand _clearAllOutputFieldsCommand;

        // 添加全部实际字段
        private ICommand _addAllActualFieldsCommand;

        // 添加映射到的推荐字段
        private ICommand _addMappedFieldsCommand;

        // 重置为默认模板
        private ICommand _resetDefaultFieldsCommand;

        // 动态获取图层字段列表
        private ObservableCollection<string> _availableFields;

        // 用于分组的实际字段列表（不包含特殊字段）
        private ObservableCollection<string> _groupableFields;

        // 显示帮助命令
        private ICommand _showHelpCommand;

        // 打开字段配置对话框命令
        private ICommand _openFieldConfigCommand;

        // 打开头部信息配置命令
        private ICommand _openHeaderConfigCommand;

        // 刷新头部配置列表命令
        private ICommand _refreshHeaderConfigsCommand;

        /// <summary>
        /// 构造函数
        /// </summary>
        public FeatureToTxtDockPaneViewModel()
        {
            try
            {
                // 初始化基本属性（必须成功）
                PolygonLayers = new ObservableCollection<FeatureLayer>();
                FieldInfos = new ObservableCollection<FieldDisplayInfo>();
                TextFormats = new ObservableCollection<string> { "UTF-8", "UTF-8(无BOM)", "ANSI", "GBK", "Unicode" };
                OutputFields = new ObservableCollection<OutputFieldItem>();
                AvailableFields = new ObservableCollection<string>();
                GroupableFields = new ObservableCollection<string>();

                StatusMessage = "正在初始化...";
                LogContent = "";
                Progress = 0;
                IsProgressIndeterminate = false;

                // 注册编码提供程序以支持GB2312、GBK等编码
                try
                {
                    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                    LogInfo("编码提供程序注册成功");

                    // 验证关键编码是否可用
                    ValidateEncodingSupport();
                }
                catch (Exception ex)
                {
                    LogError($"编码提供程序注册失败: {ex.Message}");
                }

                // 加载头部信息配置
                try
                {
                    LoadHeaderConfigs();
                }
                catch (Exception ex)
                {
                    LogError($"加载头部配置失败: {ex.Message}");
                    // 确保至少有默认配置
                    if (HeaderConfigs == null || HeaderConfigs.Count == 0)
                    {
                        HeaderConfigs = new ObservableCollection<HeaderConfig>();
                    }
                }

                // 设置默认输出路径为工程位置
                try
                {
                    SetDefaultOutputPath();
                }
                catch (Exception ex)
                {
                    LogError($"设置默认输出路径失败: {ex.Message}");
                    OutputPath = "";
                }

                // 初始化默认输出字段
                try
                {
                    InitializeDefaultOutputFields();
                }
                catch (Exception ex)
                {
                    LogError($"初始化默认输出字段失败: {ex.Message}");
                }

                LogInfo("ViewModel已初始化");
                StatusMessage = "就绪";

                // 订阅地图选择变化事件
                try
                {
                    _mapSelectionChangedToken = MapSelectionChangedEvent.Subscribe(OnMapSelectionChanged);
                }
                catch (Exception ex)
                {
                    LogError($"订阅地图选择变化事件失败: {ex.Message}");
                }

                // 初始化一次选择信息
                try
                {
                    UpdateSelectionInfo();
                }
                catch (Exception ex)
                {
                    LogError($"更新选择信息失败: {ex.Message}");
                }
            }
            catch (Exception ex)
            {
                // 如果构造函数完全失败，至少记录错误
                System.Diagnostics.Debug.WriteLine($"FeatureToTxtDockPaneViewModel构造函数失败: {ex.Message}");
                System.Diagnostics.Debug.WriteLine($"堆栈: {ex.StackTrace}");

                // 确保基本集合被初始化，避免NullReferenceException
                PolygonLayers = PolygonLayers ?? new ObservableCollection<FeatureLayer>();
                FieldInfos = FieldInfos ?? new ObservableCollection<FieldDisplayInfo>();
                TextFormats = TextFormats ?? new ObservableCollection<string> { "UTF-8", "ANSI" };
                OutputFields = OutputFields ?? new ObservableCollection<OutputFieldItem>();
                AvailableFields = AvailableFields ?? new ObservableCollection<string>();
                GroupableFields = GroupableFields ?? new ObservableCollection<string>();
                HeaderConfigs = HeaderConfigs ?? new ObservableCollection<HeaderConfig>();

                StatusMessage = $"初始化失败: {ex.Message}";
                LogContent = $"错误: {ex.Message}\n{ex.StackTrace}";

                throw; // 重新抛出异常，让上层捕获
            }
        }

        private int _logUpdateCounter = 0;
    }

    /// <summary>
    /// RelayCommand实现
    /// </summary>


    /// <summary>
    /// 泛型RelayCommand实现
    /// </summary>

}
