using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using ArcGIS.Core.CIM;
using ArcGIS.Core.Data;
using ArcGIS.Core.Geometry;
using ArcGIS.Desktop.Core;
using ArcGIS.Desktop.Framework;
using ArcGIS.Desktop.Framework.Contracts;
using ArcGIS.Desktop.Framework.Threading.Tasks;
using ArcGIS.Desktop.Mapping;
using ArcGIS.Desktop.Mapping.Events;
using ArcGIS.Desktop.Framework.Events;
using Microsoft.Win32;
using XIAOFUTools.Shared;
using XIAOFUTools.Features.Conversion.FeatureToTxt.Core;

namespace XIAOFUTools.Features.Conversion.FeatureToTxt
{
    internal partial class FeatureToTxtDockPaneViewModel
    {

        /// <summary>
        /// 设置默认输出路径为工程位置
        /// </summary>
        private void SetDefaultOutputPath()
        {
            try
            {
                var outputFolder = _outputFolderResolver.ResolveDefaultOutputFolder(Project.Current?.Path);
                if (outputFolder != null)
                {
                    OutputPath = outputFolder.Path;
                    LogInfo($"设置默认输出路径为{outputFolder.Source}: {OutputPath}");
                }
            }
            catch (Exception ex)
            {
                LogError($"设置默认输出路径时出错: {ex.Message}");
                // 如果出错，保持空路径
                OutputPath = "";
            }
        }

        /// <summary>
        /// 初始化默认输出字段
        /// </summary>
        private void InitializeDefaultOutputFields()
        {
            OutputFields.Add(new OutputFieldItem("点数", "自动根据下面点数生成", true, true));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("地块面积", "自动读取字段值", true, false));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("地块编号", "自动读取字段值", true, false));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("地块名称", "自动读取字段值", true, false));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("图形类型", "自动根据类型输出：点/线/面", true, true));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("图幅号", "自动读取字段值", true, false));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("地块用途", "自动读取字段值", true, false));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("地类编码", "自动读取字段值", true, false));
            OutputFields.Add(new OutputFieldItem(",", "分隔符", true, true));
            OutputFields.Add(new OutputFieldItem("@", "结束标记", true, true));
        }

        /// <summary>
        /// 删除输出字段
        /// </summary>
        private void RemoveOutputField(OutputFieldItem item)
        {
            if (item == null || !item.CanDelete) return;

            var index = OutputFields.IndexOf(item);
            OutputFields.Remove(item);

            // 如果删除的不是逗号，也删除前面的逗号
            if (item.FieldName != "," && index > 0 && index < OutputFields.Count + 1)
            {
                var prevItem = OutputFields.ElementAtOrDefault(index - 1);
                if (prevItem?.FieldName == ",")
                {
                    OutputFields.Remove(prevItem);
                }
            }

            NotifyPropertyChanged(() => OutputFieldsCount);
            StatusMessage = $"已删除字段 '{item.FieldName}'";
            LogInfo($"删除输出字段: {item.FieldName}");
        }

        /// <summary>
        /// 添加输出字段
        /// </summary>
        private void AddOutputField(string fieldName)
        {
            if (string.IsNullOrEmpty(fieldName)) return;
            if (fieldName.StartsWith("---") && fieldName.EndsWith("---")) return; // 忽略分隔标题

            // 检查是否已存在
            if (OutputFields.Any(f => f.FieldName == fieldName))
            {
                StatusMessage = $"字段 '{fieldName}' 已存在";
                return;
            }

            // 在@符号前插入新字段
            var atIndex = OutputFields.ToList().FindIndex(f => f.FieldName == "@");
            if (atIndex >= 0)
            {
                // 插入新字段
                var isAutoGenerated = fieldName == "点数" || fieldName == "图形类型" || fieldName == "公顷4位" || fieldName == "公顷6位";
                OutputFields.Insert(atIndex, new OutputFieldItem(fieldName, GetFieldDescription(fieldName), true, isAutoGenerated));
                // 插入逗号分隔符
                OutputFields.Insert(atIndex + 1, new OutputFieldItem(",", "分隔符", false, true));
            }

            NotifyPropertyChanged(() => OutputFieldsCount);
            StatusMessage = $"已添加字段 '{fieldName}'";
            LogInfo($"添加输出字段: {fieldName}");
        }

        /// <summary>
        /// 添加全部实际字段（根据 FieldInfos）
        /// </summary>
        private void AddAllActualFields()
        {
            if (FieldInfos == null || FieldInfos.Count == 0)
            {
                StatusMessage = "没有可用的实际字段";
                return;
            }
            var added = 0;
            foreach (var fi in FieldInfos)
            {
                var name = fi.FieldName;
                if (!OutputFields.Any(f => f.FieldName == name))
                {
                    AddOutputField(name);
                    added++;
                }
            }
            StatusMessage = added > 0 ? $"已添加 {added} 个实际字段" : "没有新增字段（均已存在）";
        }

        /// <summary>
        /// 添加映射到的推荐字段（依据 _fieldMappings 自动匹配）
        /// </summary>
        private void AddMappedFields()
        {
            if (FieldInfos == null || FieldInfos.Count == 0)
            {
                StatusMessage = "没有可用的实际字段用于匹配";
                return;
            }
            var fieldNames = FieldInfos.Select(f => f.FieldName).ToList();
            var added = 0;
            foreach (var mapping in FeatureToTxtFieldCatalog.Mappings)
            {
                var matched = FindMatchingField(fieldNames, mapping.Value);
                if (!string.IsNullOrEmpty(matched) && !OutputFields.Any(f => f.FieldName == matched))
                {
                    AddOutputField(matched);
                    added++;
                }
            }
            StatusMessage = added > 0 ? $"已添加 {added} 个推荐字段" : "未找到可添加的推荐字段";
        }

        /// <summary>
        /// 重置为默认模板
        /// </summary>
        private void ResetDefaultOutputFields()
        {
            OutputFields?.Clear();
            InitializeDefaultOutputFields();
            NotifyPropertyChanged(() => OutputFieldsCount);
            StatusMessage = "已重置为默认模板";
        }

        /// <summary>
        /// 验证编码支持
        /// </summary>
        private void ValidateEncodingSupport()
        {
            var encodingsToTest = new[]
            {
                new { Name = "GBK", CodePage = "GBK" },
                new { Name = "GB2312", CodePage = "GB2312" },
                new { Name = "Big5", CodePage = "Big5" }
            };

            foreach (var encoding in encodingsToTest)
            {
                try
                {
                    var enc = Encoding.GetEncoding(encoding.CodePage);
                    LogInfo($"编码 {encoding.Name} 支持正常 (CodePage: {enc.CodePage})");
                }
                catch (Exception ex)
                {
                    LogError($"编码 {encoding.Name} 不支持: {ex.Message}");
                }
            }
        }

        /// <summary>
        /// 清理事件订阅
        /// </summary>
        public void Cleanup()
        {
            if (_mapSelectionChangedToken != null)
            {
                MapSelectionChangedEvent.Unsubscribe(_mapSelectionChangedToken);
                _mapSelectionChangedToken = null;
            }
        }

    }
}
